### ISSUE TITLE
Error for combined mood

### ISSUE THREAD

**Issue by Nikooheb** [Derek-Wds/MAD-VAE#6]
Hi, When I want to train combined, it gives me the following error:
![image](https://user-images.githubusercontent.com/76121375/163108162-a9b1273a-ef32-462d-803d-5ffaaebe599d.png)
It is related to CE loss, It there any way to fix it?

**Comment by Derek-Wds** [comment]
Hi, thanks for the issue. It is quite strange since we already have sigmoid function at the end of the model. This error should not occur. This experiments was done two and half years ago, and as I recall, it can run successfully without any errors. 

Here are some suggestions I have: You could try to disable the GPU and see if any detailed error messages occur. Or you could try to use single GPU to see if it solves the problem. Besides, you could see if there has any invalid attack images / values being generated, which may also be a reason for this.

**Comment by Nikooheb** [comment]
Thanks, the error was related to GPU.
